---
spring:
  application:
    name: spring-cloud-client
  profiles: 
    active: dev
server:
  port: 9082
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 4
    
---    
spring:
  application:
    name: spring-eureka-server 
  profiles: 
    active: dev  
server:
  port: 9083
