---
spring:
  application:
    name: spring-config-client
  profiles: 
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 6
---    
management:
  contextPath: '/mgmt'
spring:
  application:
    name: spring-eureka-server 
  profiles: 
    active: dev  
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
---
spring:
  application:
    name: spring-eureka-client
  profiles: 
    active: dev


