---
spring:
  application:
    name: spring-config-client
  profiles: 
    active: dev
server:
  port: 9082
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 4
    
---
spring:
  application:
    name: spring-eureka-client
  profiles: 
    active: dev
server:
  port: 9086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9083/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh    
        
---    
management:
  contextPath: '/mgmt'
spring:
  application:
    name: spring-eureka-server 
  profiles: 
    active: dev  
server:
  port: 9083
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


