---
spring:
  application:
    name: spring-cloud-client
  profiles: 
    active: dev
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 2
  

