---
spring:
  application:
    name: spring-config-client
  profiles: 
    active: dev
server:
  port: 9082
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 4
    

