---
spring:
  application:
    name: spring-config-client
  profiles: 
    active: dev
server:
  port: 9082
management:
  endpoints:
    web:
      exposure:
        include: refresh
app:
  test:
    message: First Message 4
    
---    
management:
  contextPath: '/mgmt'
spring:
  application:
    name: spring-eureka-server 
  profiles: 
    active: dev  
server:
  port: 9083
eureka:
  instance:
    hostname: localhost 
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}

