---    
management:
  contextPath: '/mgmt'
spring:
  application:
    name: spring-eureka-server 
  profiles: 
    active: dev  
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
---
spring:
  application:
    name: spring-eureka-client
  profiles: 
    active: dev


